services:
  jupyter:
    image: quay.io/jupyter/datascience-notebook:latest
    container_name: jupyter_ds_stack
    ports:
      - "8888:8888"
    volumes:
      # Project files: Bind mounted for easy editing from WSL/VS Code
      - ./work:/home/jovyan/work
      # Persistent Depot: Stores packages and precompiled binaries
      - /home/gary/projects/julia_depot:/home/jovyan/.julia
    environment:
      - JUPYTER_TOKEN=my-prosperity-token
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    restart: always